server:
  port: 8080
cube:
  data:
    host: 25.30.15.85
  crypto:
    aes-key: ''
  resources:
    #文件上传根目录 设置
    upload-path: /app/files
    #webapp文件路径
    webapp: /app/webapp
# 自定义输出日志
logging:
  group:
    system: com.tievd.cube
  level:
    system: DEBUG
spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://${cube.data.host}/cube?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: chengxun
          driver-class-name: com.mysql.cj.jdbc.Driver
          lazy: true
  redis:
    database: 0
    host: ${cube.data.host}
    port: 6379
    password: ''
  mail:
    host: smtp.163.com
    username: cube@163.com
    password: ??
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true