server:
  port: 9111
spring:
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      ui:
        title: 魔方微服务监控中心
      client:
        instance:
          metadata:
            tags:
              environment: local
  security:
    user:
      name: admin
      password: admin
  application:
    name: cube-monitor
  cloud:
    nacos:
      discovery:
        server-addr: 25.30.15.85:8848
# 服务端点检查
management:
  trace:
    http:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always