# 魔方基础服务-微服务开发环境配置
cube:
  resources:
    #文件上传根目录 设置
    upload-path: /app/files
    #webapp文件路径
    webapp: /app/webapp
  apr:
    enable-tomcat-native: false
  crypto:
    aes-key: ''
    sm4-key: ''
    rsa-public-key: ''
    rsa-private-key: ''
    sm2-public-key: ''
    sm2-private-key: ''
  route:
    # 微服务路由管理 yml | nacos | database
    config:
      data-id: cube-gateway-router
      group: DEFAULT_GROUP
      data-type: nacos
  data:
    host: 25.30.15.85
# 自定义输出日志
logging:
  group:
    system: org.jeecg.modules.system.mapper, com.tievd.cube.system.modules
  level:
    system: DEBUG
spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://${cube.data.host}/cube?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: chengxun
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 7
    host: ${cube.data.host}
    port: 6379
    password: ''
  mail:
    host: smtp.163.com
    username: cube@163.com
    password: ??
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true